#pragma once

#include <cstddef>

/**
 * ICAO airline codes -> display names, sorted by code for binary
 * search. Generated by scripts/build_airlines.py.
 *
 * Source: OpenFlights (https://openflights.org/data.html),
 * Open Database License (ODbL).
 */
namespace data::airlines {

struct Airline {
  char icao[4];
  const char* name;
};

constexpr size_t kAirlineCount = 5771;
constexpr size_t kMaxNameLen = 16;
extern const Airline kAirlines[kAirlineCount];

}  // namespace data::airlines
