#!/usr/bin/env python3
"""Build the embedded ICAO airline-code table from OpenFlights.

The radar shows a callsign like "DLH4AB"; its first three letters are the
airline's ICAO code. This turns that prefix into "Lufthansa".

Data: OpenFlights airlines.dat, available under the Open Database License
(ODbL). Attribution is carried in the generated header and in the README.

Names are trimmed to what a 240 px round display can show; entries whose name
would be unreadable or is missing are dropped rather than shown truncated to
nonsense.

Usage: python3 scripts/build_airlines.py
"""

from __future__ import annotations

import csv
import io
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_H = ROOT / "include" / "data" / "airlines.h"
OUT_CPP = ROOT / "src" / "data" / "airlines_data.cpp"

SOURCE_URL = (
    "https://raw.githubusercontent.com/jpatokal/openflights/master/data/"
    "airlines.dat"
)

# Longest name the tag block can carry without swallowing the radar.
MAX_NAME = 16

# Suffixes that add nothing once the name is already identifying it.
SUFFIXES = (
    " (Pty) Ltd", " Pty Ltd", " Ltd.", " Ltd", " Inc.", " Inc", " LLC",
    " Co.", " Company", " Limited", " GmbH", " S.A.", " SA", " AG", " N.V.",
    " Corporation", " Corp.", " Corp",
)


def fetch_rows() -> list[list[str]]:
    with urllib.request.urlopen(SOURCE_URL, timeout=60) as resp:
        text = resp.read().decode("utf-8", errors="replace")
    return list(csv.reader(io.StringIO(text)))


def clean_name(raw: str) -> str | None:
    name = raw.strip().strip('"').strip()
    if not name or name in {"\\N", "Unknown", "Private flight"}:
        return None
    for suffix in SUFFIXES:
        if name.endswith(suffix):
            name = name[: -len(suffix)].strip()
    # Drop a parenthesised qualifier: "Air Berlin (Topbonus)" -> "Air Berlin".
    name = re.sub(r"\s*\([^)]*\)\s*$", "", name).strip()
    # The display font covers printable ASCII only.
    name = name.encode("ascii", "ignore").decode("ascii").strip()
    if len(name) < 2:
        return None
    return name[:MAX_NAME].strip()


def build() -> list[tuple[str, str]]:
    by_code: dict[str, str] = {}
    for row in fetch_rows():
        if len(row) < 8:
            continue
        icao = row[4].strip().strip('"').upper()
        if len(icao) != 3 or not icao.isalpha():
            continue
        name = clean_name(row[1])
        if name is None:
            continue
        active = row[7].strip().strip('"') == "Y"
        # Several rows share a code (renames, successors). Prefer the one still
        # flagged active, otherwise keep the first seen.
        if icao not in by_code or active:
            by_code[icao] = name
    return sorted(by_code.items())


def write(entries: list[tuple[str, str]]) -> None:
    OUT_H.write_text(
        "#pragma once\n\n"
        "#include <cstddef>\n\n"
        "/**\n"
        " * ICAO airline codes -> display names, sorted by code for binary\n"
        " * search. Generated by scripts/build_airlines.py.\n"
        " *\n"
        " * Source: OpenFlights (https://openflights.org/data.html),\n"
        " * Open Database License (ODbL).\n"
        " */\n"
        "namespace data::airlines {\n\n"
        "struct Airline {\n"
        "  char icao[4];\n"
        "  const char* name;\n"
        "};\n\n"
        f"constexpr size_t kAirlineCount = {len(entries)};\n"
        f"constexpr size_t kMaxNameLen = {MAX_NAME};\n"
        "extern const Airline kAirlines[kAirlineCount];\n\n"
        "}  // namespace data::airlines\n",
        encoding="utf-8",
    )

    lines = [
        "// Generated by scripts/build_airlines.py -- do not edit.",
        "// Source: OpenFlights (https://openflights.org/data.html), ODbL.",
        "",
        '#include "data/airlines.h"',
        "",
        "namespace data::airlines {",
        "",
        "const Airline kAirlines[kAirlineCount] = {",
    ]
    for icao, name in entries:
        escaped = name.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    {{"{icao}", "{escaped}"}},')
    lines += ["};", "", "}  // namespace data::airlines", ""]
    OUT_CPP.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    entries = build()
    write(entries)
    approx = sum(len(n) + 1 + 8 for _, n in entries)
    print(f"{len(entries)} airlines, ~{approx // 1024} KB of flash")
    print(f"  {OUT_H.relative_to(ROOT)}")
    print(f"  {OUT_CPP.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
